-- Create users table CREATE TABLE IF NOT EXISTS users (     id SERIAL PRIMARY KEY,     email VARCHAR(255) UNIQUE NOT NULL,     username VARCHAR(100) UNIQUE NOT NULL,     oauth_provider VARCHAR(50) NOT NULL,     oauth_id VARCHAR(255) NOT NULL,     role VARCHAR(20) NOT NULL DEFAULT 'player',     avatar_url VARCHAR(500),     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,     last_login TIMESTAMP WITH TIME ZONE,     CONSTRAINT unique_oauth UNIQUE(oauth_provider, oauth_id),     CONSTRAINT check_role CHECK (role IN ('admin', 'player', 'spectator')) );  CREATE INDEX idx_users_email ON users(email); CREATE INDEX idx_users_oauth ON users(oauth_provider, oauth_id); CREATE INDEX idx_users_role ON users(role); 

-- Create games table CREATE TABLE IF NOT EXISTS games (     id SERIAL PRIMARY KEY,     room_code VARCHAR(10) UNIQUE NOT NULL,     state VARCHAR(20) NOT NULL DEFAULT 'waiting',     phase INTEGER DEFAULT 1,     current_player_position INTEGER,     trump_suit VARCHAR(10),     deck_cards JSONB DEFAULT '[]'::jsonb,     table_cards JSONB DEFAULT '[]'::jsonb,     created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,     started_at TIMESTAMP WITH TIME ZONE,     finished_at TIMESTAMP WITH TIME ZONE,     winner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,     max_players INTEGER DEFAULT 8 CHECK (max_players >= 2 AND max_players <= 8),     CONSTRAINT check_state CHECK (state IN ('waiting', 'phase1', 'phase2', 'finished', 'cancelled')),     CONSTRAINT check_phase CHECK (phase IN (1, 2)) );  CREATE INDEX idx_games_state ON games(state); CREATE INDEX idx_games_room_code ON games(room_code); CREATE INDEX idx_games_created_by ON games(created_by); 

-- Create game_players table CREATE TABLE IF NOT EXISTS game_players (     id SERIAL PRIMARY KEY,     game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,     user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,     position INTEGER NOT NULL,     cards JSONB DEFAULT '[]'::jsonb,     top_card JSONB,     card_count INTEGER DEFAULT 0,     status VARCHAR(20) DEFAULT 'active',     can_call_cheat BOOLEAN DEFAULT true,     joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,     CONSTRAINT unique_game_user UNIQUE(game_id, user_id),     CONSTRAINT unique_game_position UNIQUE(game_id, position),     CONSTRAINT check_status CHECK (status IN ('active', 'eliminated', 'winner', 'left')) );  CREATE INDEX idx_game_players_game ON game_players(game_id); CREATE INDEX idx_game_players_user ON game_players(user_id); CREATE INDEX idx_game_players_position ON game_players(game_id, position); 

-- Create game_actions table (for audit log and game history) CREATE TABLE IF NOT EXISTS game_actions (     id SERIAL PRIMARY KEY,     game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,     user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,     action_type VARCHAR(50) NOT NULL,     action_data JSONB,     phase INTEGER,     timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,     CONSTRAINT check_action_type CHECK (action_type IN (         'join', 'leave', 'start_game', 'draw_card', 'place_card',         'call_cheat', 'receive_penalty', 'phase_change',         'take_table_card', 'skip_turn', 'win', 'lose'     )) );  CREATE INDEX idx_game_actions_game ON game_actions(game_id); CREATE INDEX idx_game_actions_user ON game_actions(user_id); CREATE INDEX idx_game_actions_timestamp ON game_actions(timestamp); CREATE INDEX idx_game_actions_type ON game_actions(action_type); 


